SIM ?= questa
TOPLEVEL_LANG ?= vhdl
#VHDL_SOURCES ?= ../rtl/*.vhd
TOPLEVEL = processor
MODULE = test_instr
# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim